pipeline:
  build:
    image: jekyll/jekyll:latest
    commands:
      - touch Gemfile.lock
      - chmod a+w Gemfile.lock
      - chown -R jekyll:jekyll /drone/src
      - gem update --system
      - gem install bundler
      - bundle install
      - bundle exec jekyll build 
      
  push:
    image: drillster/drone-rsync
    hosts: 
      from_secret: swarm_host
    key:
      from_secret: swarm_key
    source: _site/*
    target: ~/example.com
    recursive: true
    user:
      from_secret: swarm_user
    delete: true
    script:
      - chmod -R 755 ~/example.com
    when:
      event: [push]
    
  context:
    image: appleboy/drone-scp
    host: 
      from_secret: swarm_host
    username:
      from_secret: swarm_user
    key:
      from_secret: swarm_key
    target: /root/context
    source: /drone
    when:
      event: [push]
      
  context-ssh:
    image: appleboy/drone-ssh
    host: 
      from_secret: swarm_host
    username:
      from_secret: swarm_user
    key:
      from_secret: swarm_key
    port: 22
    script:
      - docker stack deploy -c /root/example.com/docker-stack.yml apps
    when:
      event: [push]  
    
  deploy:
    image: ruanbekker/docker-remote-tunnel
    secrets: [ swarm_key, swarm_host ]
    commands:
    - echo $${SWARM_KEY} > /tmp/key
    - docker-tunnel -c root@$${SWARM_HOST}
    - source /root/.docker-tunnel.sh
    - docker node ls
    - docker-tunnel --terminate
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      event: [push]
      branch: [master, develop, release/*]

