pipeline:      
  build:
    image: jekyll/jekyll:latest
    environment:
      - BUNDLE_PATH=/drone/.bundle
    commands:
      - touch Gemfile.lock
      - chmod a+w Gemfile.lock
      - chown -R jekyll:jekyll /drone/src
      - gem update --system
      - gem install bundler
      - bundle install
      - bundle exec jekyll build
      
  qux:
    image: golang:1.7
    group: test
    commands:
      - echo step 3
      - sleep 10
      - echo done 3
  quux:
    image: golang:1.7
    group: test
    commands:
      - echo step 4
      - sleep 10
      - echo done 4
      
  push:
    image: drillster/drone-rsync
    hosts: 
      from_secret: swarm_host
    key:
      from_secret: swarm_key
    source: _site/*
    target: ~/example.com
    recursive: true
    user:
      from_secret: swarm_user
    delete: true
    script:
      - chmod -R 755 ~/example.com
    when:
      event: [push]
      
  deploy:
    image: appleboy/drone-ssh
    host: 
      from_secret: swarm_host
    username:
      from_secret: swarm_user
    key:
      from_secret: swarm_key
    port: 22
    script:
      - docker stack deploy -c /root/example.com/docker-stack.yml apps
    when:
      event: [push]  
    
  
