pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - /drone/.bundle
    volumes:
      - /tmp:/cache
      
  build:
    image: jekyll/jekyll:latest
    environment:
      - BUNDLE_PATH=/drone/.bundle
    commands:
      - touch Gemfile.lock
      - chmod a+w Gemfile.lock
      - chown -R jekyll:jekyll /drone/src
      - gem update --system
      - gem install bundler
      - bundle install
      - bundle exec jekyll build
      - touch data.txt
      - hostname > data.txt
      
  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - /drone/.bundle
    volumes:
      - /tmp:/cache
      
  debug:
    image: alpine
    commands:
      - ls -lah
      - find .
      - pwd
      - cat data.txt
      - hostname >> data.txt
  
  debug2:
    image: alpine
    commands:
      - ls -lah
      - find .
      - pwd
      - cat data.txt
      - hostname >> data.txt
      - cat data.txt
      
  push:
    image: drillster/drone-rsync
    hosts: 
      from_secret: swarm_host
    key:
      from_secret: swarm_key
    source: _site/*
    target: ~/example.com
    recursive: true
    user:
      from_secret: swarm_user
    delete: true
    script:
      - chmod -R 755 ~/example.com
    when:
      event: [push]
      
  deploy:
    image: appleboy/drone-ssh
    host: 
      from_secret: swarm_host
    username:
      from_secret: swarm_user
    key:
      from_secret: swarm_key
    port: 22
    script:
      - docker stack deploy -c /root/example.com/docker-stack.yml apps
    when:
      event: [push]  
      
