pipeline:
  build:
    image: ruby
    commands:
      - find / -name Gemfile
      - gem install bundler
      - bundle install
      - bundle exec jekyll build
      
  push:
    image: drillster/drone-rsync
    hosts: 
      from_secret: swarm_host
    key:
      from_secret: swarm_key
    source: _site/*
    target: ~/example.com
    recursive: true
    user:
      from_secret: swarm_user
    delete: true
    
  deploy:
    image: alpine
    environment:
      MYKEY:
        from_secret: swarm_key
    commands:
      - echo $MYKEY > /tmp/key
      - cat /tmp/key
