pipeline:
  build:
    image: ruby
    commands:
      - gem install bundler
      - bundle install
      - bundle exec jekyll build
      
  push:
    image: drillster/drone-rsync
    hosts: 
      from_secret: swarm_host
    key:
      from_secret: swarm_key
    source: _site/*
    target: ~/example.com
    recursive: true
    user:
      from_secret: swarm_user
    delete: true
    
  context:
    image: appleboy/drone-scp
    host: 
      from_secret: swarm_host
    username:
      from_secret: swarm_user
    key:
      from_secret: swarm_key
    target: /root/context
    source: /root
    when:
      event: [push]
    
  deploy:
    image: ruanbekker/docker-remote-tunnel
    secrets: [ swarm_key, swarm_host ]
    commands:
    - ls /
    - echo $${SWARM_KEY} > /tmp/key
    - docker-tunnel -c root@51.15.93.65
    - export DOCKER_HOST="localhost:2376"
    - docker service ls
    when:
      branch: [master, develop, release/*]
