pipeline:
  build:
    image: ruby
    commands:
      - find .
      - gem install bundler
      - bundle install
      - bundle exec jekyll build
      
  deploy:
    image: drillster/drone-rsync
    hosts: 
      from_secret: swarm_host
    key:
      from_secret: swarm_key
    source: _site/*
    target: ~/example.com
    recursive: true
    user:
      from_secret: swarm_user
    delete: true
